### PR TITLE
Cargo.toml: Use SPDX license identifier so crates.io won't show "non-standard"

### PR DESCRIPTION
**Pull request by joshtriplett**
Cargo.toml currently references the GPL as a custom license file, which
makes the crate show up on crates.io as having a "non-standard" license.
Use an SPDX identifier instead, so that crates.io will show the actual
license.

### CODE REVIEW

**Comment by joshtriplett** [comment]
Inspired by finding async-rdma on crates.io, seeing "non-standard" and thinking I might not be able to use it, looking in the git repo, and then going "oh, that's just the GPL".

**Comment by GTwhy** [comment]
Hi, @joshtriplett , thanks for your pr : )

**Review by GTwhy — APPROVED** [review]

**Comment by GTwhy** [comment]
Hi @joshtriplett , do you think MIT is better, or the GPL MIT dual license?

**Comment by joshtriplett** [comment]
I have no problem with choosing the GPL; that's a crate maintainer's decision. I wish more useful crates would.

**Comment by GTwhy** [comment]
Ok, let's stick with the GPL for now.

**Pull request merged**
